<a href="https://colab.research.google.com/github/darshil6/Darshil-Project/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([[1,2,3,4,56],[12,984,64,98,468]])

In [45]:
print(a.ndim)
print(b.ndim)

1
2


In [46]:
print(a.dtype)
print(b.itemsize)
print(b.size)
print(a.size)
print(a.shape)
print(b.shape)

int64
8
10
4
(4,)
(2, 5)


In [47]:
np.zeros([5,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
print(np.arange(0,11))
print(np.arange(0,11,2))

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10]


In [49]:
np.linspace(1,10,15)

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

In [50]:
a.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [54]:
b.sum(axis=1)

array([  66, 1626])

In [57]:
np.sqrt(b)

array([[ 1.        ,  1.41421356,  1.73205081,  2.        ,  7.48331477],
       [ 3.46410162, 31.36877428,  8.        ,  9.89949494, 21.63330765]])